name: MobSF Analysis


# ------------------------------------------------------------------------------


on:
  push:
    branches:
      - main
      - topic/devops
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]


# ------------------------------------------------------------------------------


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# ------------------------------------------------------------------------------


jobs:

  # Job
  mobsf-scanning:
    name: MobSF Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    timeout-minutes: 15
    steps:

      # Step
      - name: Checkout
        uses: actions/checkout@v5

      # Step
      - name: Install PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step
      - name: Install MOB-SF
        run: pip install mobsfscan

      # Step
      - name: Analysis
        id: scan
        shell: bash
        run: |
          mobsfscan --sarif --output mobsfscan.sarif . --no-fail
          
          if [ -f "mobsfscan.sarif" ]; then
            echo "SARIF report generated successfully."
          
            FINDINGS_COUNT=$(jq '.runs[0].results // [] | length' mobsfscan.sarif 2>/dev/null || echo 0)
            echo "Number of findings: $FINDINGS_COUNT"
            if [ "$FINDINGS_COUNT" -gt 0 ]; then
              echo "FAILED=true" >> $GITHUB_OUTPUT
            else
              echo "FAILED=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "SARIF file was not created."
            echo "FAILED=true" >> $GITHUB_OUTPUT
          fi

      # Step
      - name: Output in Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: mobsfscan.sarif

      # Step
      - name: Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-sarif
          path: mobsfscan.sarif

      # Step
      - name: Notify
        if: steps.scan.outputs.FAILED == 'true'
        run: |
          echo "Log:"
          echo "❌ MobSF scan failed due to security findings or an error."
          echo "   Check the logs and the uploaded SARIF report.          "


# ------------------------------------------------------------------------------